### ISSUE TITLE
Idea: Use champion winrate data to determine whether a champion should be included for a nonstandard role

### ISSUE THREAD

**Issue by Hailfire805** [TheRaphael0000/tahm-ken.ch#12]
# Overview
The current priority system and "Stupidity level score" use hardcoded lists to determine what position each champion should be valid for assignment in team comp generation. 

A more effective method to handle this step would be to utilize champion winrate data when played in positions other than the hardcoded position. This way, champions who are very strong in less common positions can also be included in the calculations.

## Examples Of Champions That Could Be Used If This Method Was Added

| Champion    | Position | Pickrate 13.24 All Rank | Pickrate 13.24 Emerald +  | Winrate 13.24   |
|-------------|----------|-------------------------|---------------------------|-----------------|  
| Karthus     | Bottom   | 0.26%                   | 0.48%                     | (53.74 / 54.49) |
| Cassiopeia  | Top      | 0.29%                   | 0.45%                     | (51.39 / 53.21) |
| Camille     | Middle   | 0.11%                   | 0.15%                     | (52.35 / 55.10) |
| Brand       | Jungle   | 3.59%                   | 4.93%                     | (51.81 / 52.22) |
| Zac         | Support  | 0.45%                   | 0.63%                     | (52.56 / 53.11) |

**Comment by TheRaphael0000** [comment]
Hi,
This is a good idea. We could use a kind of metric by computing the geometric mean (or another function I need to think a bit more about it) of the pick rate of the composition
I would just need a good way to obtain the pickrates for each champion at each role across all patches.
I don't intend to do game analysis myself but if I can find someone who provide this data for free that would be a great improvement :)
Thanks for the feedback !

**Comment by TheRaphael0000** [comment]
Hi,
I forgot to close this issue. I've found a way to implement this 2 months ago.

Op.gg has a undocumented API for winrates: https://lol-web-api.op.gg/api/v1.0/internal/bypass/champions/euw/ranked

Comps are now ordered by a "attribution score" using this algorithm:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html

You can find the change here if interested.
https://github.com/TheRaphael0000/tahm-ken.ch/commit/9aff4d74cc4908ca9acb5aa1d91bfc1bd6623dc9

Thanks!
