### ISSUE TITLE
API: return application/json instead of text/html

### ISSUE THREAD

**Issue by DarkIntaqt** [TheRaphael0000/tahm-ken.ch#14]
The API currently returns text/html even tho the content is JSON. So why not change the API MIME-type. That should be easily doable and conforms to more standards

**Comment by TheRaphael0000** [comment]
Hi,
Thanks didn't notice. Fixed with https://github.com/TheRaphael0000/tahm-ken.ch/commit/231107530fb1e4570a82d6dc8c69c8655b1edcf1
