### ISSUE TITLE
Filter problem with multiple challenge section

### ISSUE THREAD

**Issue by celiendonze** [TheRaphael0000/tahm-ken.ch#5]
When selecting a first filter, the second one is not updated with the available champions.
![image](https://user-images.githubusercontent.com/16205407/183768819-33638b9d-cdfc-436c-b165-6eaa95c3ab0a.png)

**Comment by TheRaphael0000** [comment]
Thank you for your feedback. I've improve the filters accordingly to your request. The change is now live.
